# .circleci/config.yml
version: 2.1
jobs:
  test-only:
    macos:
      xcode: 15.0.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: ios test
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_test_results:
          path: output/scan

workflows:
  build-test-lint:
    jobs:
      - test-only
