# fastlane/Fastfile

platform :mac do
  before_all do
    setup_circle_ci
  end

  desc "Run Tests In Mac"
  lane :test do
    run_tests(
      scheme: "EssentialFeedPractice",
      force_quit_simulator: true,
      include_simulator_logs: false,
      clean: true
    )
  end
end