# fastlane/Fastfile
default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Run macOS Tests"
  lane :macTest do
    run_tests(
      scheme: "EssentialFeedPractice",
      force_quit_simulator: true,
      include_simulator_logs: false,
      clean: true
    )
  end
end