# fastlane/Fastfile
default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Run iOS Tests"
  lane :iOSTest do
    scan
  end
end

platform :mac do
  before_all do
    setup_circle_ci
  end

  desc "Run macOS Tests"
  lane :macTest do
    run_tests(
      scheme: "EssentialFeedPractice",
      clean: true
    )
  end
end