name: CI-iOS

on:
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-test"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: macos-13

    timeout-minutes: 30

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.0.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
      
    - name: Build and Test
      run: xcodebuild test -workspace EssentialApp/EssentialApp.xcworkspace -scheme "EssentialFeedPracticeiOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15,OS=17.0" ONLY_ACTIVE_ARCH=YES